In [26]:
import pandas as pd

In [27]:
df=pd.read_csv('pizza_sales.csv')
df.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  object
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: float64(2), int64(3), object(7)
memory usage: 4.5+ MB

In [29]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
48615    False
48616    False
48617    False
48618    False
48619    False
Length: 48620, dtype: bool

In [30]:
#data cleaning
duplicates=df[df.duplicated()]
duplicates

Empty DataFrame
Columns: [pizza_id, order_id, pizza_name_id, quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name]
Index: []

In [31]:
int_float=df.select_dtypes(['int64','float64'])
int_float

       pizza_id  order_id  quantity  unit_price  total_price
0             1         1         1       13.25        13.25
1             2         2         1       16.00        16.00
2             3         2         1       18.50        18.50
3             4         2         1       20.75        20.75
4             5         2         1       16.00        16.00
...         ...       ...       ...         ...          ...
48615     48616     21348         1       16.75        16.75
48616     48617     21348         1       17.95        17.95
48617     48618     21348         1       12.00        12.00
48618     48619     21349         1       20.25        20.25
48619     48620     21350         1       12.75        12.75

[48620 rows x 5 columns]

In [32]:
quantity_skew=df['quantity'].skew()
unit_price_skew=df['unit_price'].skew()
total_price_skew=df['total_price'].skew()

print(quantity_skew)
print(unit_price_skew)
print(total_price_skew)

7.676100461897607
0.1274191538833561
1.7328564007150935

In [33]:
df['quantity'].unique()

array([1, 2, 3, 4])

In [34]:
df['unit_price'].unique()

array([13.25, 16.  , 18.5 , 20.75, 16.5 , 12.75, 12.  , 12.5 , 20.5 ,
       20.25, 16.75, 15.25, 17.95, 16.25, 14.75,  9.75, 17.5 , 10.5 ,
       25.5 , 11.  , 14.5 , 12.25, 21.  , 23.65, 35.95])

In [35]:
df['total_price'].unique()

array([13.25, 16.  , 18.5 , 20.75, 16.5 , 12.75, 12.  , 12.5 , 20.5 ,
       20.25, 16.75, 15.25, 17.95, 16.25, 14.75, 32.  ,  9.75, 17.5 ,
       10.5 , 25.5 , 11.  , 14.5 , 12.25, 21.  , 62.25, 41.5 , 50.25,
       23.65, 24.  , 33.5 , 35.9 , 25.  , 19.5 , 37.5 , 37.  , 41.  ,
       33.  , 40.5 , 24.5 , 47.3 , 22.  , 35.95, 29.  , 29.5 , 26.5 ,
       48.75, 32.5 , 30.5 , 48.  , 51.  , 36.  , 35.  , 83.  , 61.5 ,
       49.5 , 55.5 ])

In [36]:
#feature engineering

In [37]:
df['order_date']=pd.to_datetime(df['order_date'],format='mixed')
df['order_time']=pd.to_datetime(df['order_time'],format='mixed')

In [38]:
df['order_hour']=df['order_time'].dt.hour#extract hour
df['order_month']=df['order_date'].dt.month_name()#extract month name
df['month_id']=df['order_date'].dt.month#extract month number
df['order_day']=df['order_date'].dt.day_name()#extract day name

In [39]:
day_num={
    'Sunday':1,
    'Monday':2,
    'Tuesday':3,
    'Wednesday':4,
    'Thursday':5,
    'Friday':6,
    'Saturday':7
}
df['day_id']=df['order_day'].map(day_num)

In [51]:
#function banaune
def currencyConverter(dataframe,*args):
    for col in args:
        dataframe[col]=dataframe[col].map("Rs.{:,.2f}".format)
def pctConverter(dataframe, *args):
    for col in args:
        dataframe[col]=dataframe[col].map("Rs.{:,.2f}%".format)

In [52]:
'''Key Performance Indicators (KPIs) 
Total Revenue = Sum of total_price 
Total Pizzas Sold = Sum of quantity 
Total Orders = Count of unique order_id 
Average Order Value (AOV) = Total Revenue ÷ Total Orders 
Average Pizza per Order = Total Pizzas Sold ÷ Total Orders '''
#KPI'S

'Key Performance Indicators (KPIs) \nTotal Revenue = Sum of total_price \nTotal Pizzas Sold = Sum of quantity \nTotal Orders = Count of unique order_id \nAverage Order Value (AOV) = Total Revenue ÷ Total Orders \nAverage Pizza per Order = Total Pizzas Sold ÷ Total Orders '

In [53]:
total_revenue=df['total_price'].sum()
total_revenue

np.float64(817860.0499999999)

In [54]:
total_revenue=df['total_price'].sum()
total_pizza_sold=df['quantity'].sum()
#nunique->number of total unique orders
total_orders=df['order_id'].nunique()
average_order_value=total_revenue/total_orders
average_pizza_per_order=total_pizza_sold/total_orders

In [55]:
print(f'Total Revenue : Rs.{total_revenue:,.2f}')
print(f'Total Pizza Sold:{total_pizza_sold}qty.')
print(f'Total Orders: {total_orders}.')
print(f'Average Order Value:Rs {average_order_value:,.2f}')
print(f'Average Pizza Per Order: {average_pizza_per_order:,.2f}.')

Total Revenue : Rs.817,860.05
Total Pizza Sold:49574qty.
Total Orders: 21350.
Average Order Value:Rs 38.31
Average Pizza Per Order: 2.32.

In [56]:
#analysis
##daily trend sales by day of week
daily_trend=df.groupby(['day_id','order_day'])['total_price'].sum().reset_index().rename(
    columns={'order_day': 'Order Day','total_price':'Total Price'}
)
currencyConverter(daily_trend,'Total Price')
daily_trend[['Order Day','Total Price']]

   Order Day    Total Price
0     Sunday  Rs.102,116.45
1     Monday  Rs.110,471.60
2    Tuesday  Rs.115,594.45
3  Wednesday  Rs.116,731.20
4   Thursday  Rs.121,650.30
5     Friday  Rs.129,690.90
6   Saturday  Rs.121,605.15

In [57]:
####hourly trend: sales by hour of day
hourly_trend=df.groupby('order_hour')['total_price'].sum().reset_index().rename(
    columns={'order_hour':'Order Hour','total_price':'Total Price'}
)
currencyConverter(hourly_trend,'Total Price')
hourly_trend[['Order Hour','Total Price']]

    Order Hour    Total Price
0            9       Rs.83.00
1           10      Rs.303.65
2           11   Rs.44,935.80
3           12  Rs.111,877.90
4           13  Rs.106,065.70
5           14   Rs.59,201.40
6           15   Rs.52,992.30
7           16   Rs.70,055.40
8           17   Rs.86,237.45
9           18   Rs.89,296.85
10          19   Rs.72,628.90
11          20   Rs.58,215.40
12          21   Rs.42,029.80
13          22   Rs.22,815.15
14          23    Rs.1,121.35

In [58]:
#monthly trend :monthly revenue and orders
monthly_trend=df.groupby(['month_id','order_month']).agg(
    total_price=('total_price','sum'),
    total_orders=('order_id','nunique')
).reset_index().rename(
    columns={'order_month':'Order Month','total_price':'Total Price','total_orders':'Total Orders'}
)
currencyConverter(monthly_trend,'Total Price')
monthly_trend[['Order Month','Total Price','Total Orders']]

   Order Month   Total Price  Total Orders
0      January  Rs.71,620.15          1929
1     February  Rs.64,419.45          1648
2        March  Rs.71,301.40          1864
3        April  Rs.70,312.00          1829
4          May  Rs.67,648.80          1765
5         June  Rs.68,161.45          1771
6         July  Rs.70,880.65          1860
7       August  Rs.69,497.30          1835
8    September  Rs.63,803.70          1638
9      October  Rs.68,152.20          1782
10    November  Rs.71,004.85          1844
11    December  Rs.61,058.10          1585

In [59]:
#new day june 22

In [60]:

#% of sales by category
cat_sales_pct = df.groupby('pizza_category')['total_price'].sum().reset_index()
cat_sales_pct['sales_pct'] = (cat_sales_pct['total_price'] / total_revenue)*100
currencyConverter(cat_sales_pct, 'total_price')
pctConverter(cat_sales_pct, 'sales_pct')
cat_sales_pct.rename(columns = {
    'pizza_category': 'Pizza Category',
    'total_price': 'Total Price',
    'sales_pct': 'Sales Pct'
})

  Pizza Category    Total Price  Sales Pct
0        Chicken  Rs.195,919.50  Rs.23.96%
1        Classic  Rs.220,053.10  Rs.26.91%
2        Supreme  Rs.208,197.00  Rs.25.46%
3         Veggie  Rs.193,690.45  Rs.23.68%

In [61]:
#% of sales by pizza size and category
size_cat_sales_pct = df.groupby(['pizza_size', 'pizza_category'])['total_price'].sum().reset_index()
size_cat_sales_pct['sales_pct'] = (size_cat_sales_pct['total_price'] / total_revenue)*100

currencyConverter(size_cat_sales_pct, 'total_price')
pctConverter(size_cat_sales_pct, 'sales_pct')
size_cat_sales_pct.rename(columns = {
    'pizza_size': 'Pizza Size',
    'pizza_category': 'Pizza Category',
    'total_price': 'Total Price',
    'sales_pct': 'Sales Pct'
})

   Pizza Size Pizza Category    Total Price  Sales Pct
0           L        Chicken  Rs.102,339.00  Rs.12.51%
1           L        Classic   Rs.74,518.50   Rs.9.11%
2           L        Supreme   Rs.94,258.50  Rs.11.53%
3           L         Veggie  Rs.104,202.70  Rs.12.74%
4           M        Chicken   Rs.65,224.50   Rs.7.98%
5           M        Classic   Rs.60,581.75   Rs.7.41%
6           M        Supreme   Rs.66,475.00   Rs.8.13%
7           M         Veggie   Rs.57,101.00   Rs.6.98%
8           S        Chicken   Rs.28,356.00   Rs.3.47%
9           S        Classic   Rs.69,870.25   Rs.8.54%
10          S        Supreme   Rs.47,463.50   Rs.5.80%
11          S         Veggie   Rs.32,386.75   Rs.3.96%
12         XL        Classic   Rs.14,076.00   Rs.1.72%
13        XXL        Classic    Rs.1,006.60   Rs.0.12%

In [63]:
#total pizza sold by pizza category
pizza_sold_cat = df.groupby('pizza_category')['quantity'].sum().reset_index().rename(
    columns = {'pizza_category': 'Pizza Category', 'quantity': 'Total Pizza Sold'}
)
pizza_sold_cat['Total Pizza Sold'] = pizza_sold_cat['Total Pizza Sold'].map("{:,.2f} qty".format)
pizza_sold_cat

  Pizza Category Total Pizza Sold
0        Chicken    11,050.00 qty
1        Classic    14,888.00 qty
2        Supreme    11,987.00 qty
3         Veggie    11,649.00 qty

In [65]:
# top-5 best selling pizzas 
top_5=df.groupby('pizza_name').agg(
    total_revenue=('total_price','sum'),
    total_orders=('order_id','nunique'),
    total_sold=('quantity','sum'),
).reset_index().sort_values(ascending=False,by='total_revenue',ignore_index=True).head()
currencyConverter(top_5,'total_revenue')
top_5['total_orders']=top_5['total_orders'].map('{:,.0f}'.format)
top_5['total_sold']=top_5['total_sold'].map('{:,.0f} qty'.format)
top_5.rename(columns={
    'pizza_name':'Pizza Name','total_revenue':'Total Revenue','total_orders':'Total Orders',
    'total_sold':'Total Sold'
})

                     Pizza Name Total Revenue Total Orders Total Sold
0        The Thai Chicken Pizza  Rs.43,434.25        2,225  2,371 qty
1    The Barbecue Chicken Pizza  Rs.42,768.00        2,273  2,432 qty
2  The California Chicken Pizza  Rs.41,409.50        2,197  2,370 qty
3      The Classic Deluxe Pizza  Rs.38,180.50        2,329  2,453 qty
4       The Spicy Italian Pizza  Rs.34,831.25        1,822  1,924 qty

In [67]:
#bottom 5 least selling pizzas
bottom_5 = df.groupby('pizza_name').agg(
    total_revenue = ('total_price', 'sum')
).reset_index().sort_values(ascending=True, by='total_revenue', ignore_index=True).head()

currencyConverter(bottom_5, 'total_revenue')
bottom_5.rename(columns = {
    'pizza_name': 'Pizza Name', 'total_revenue': 'Total Revenue'
})

                  Pizza Name Total Revenue
0       The Brie Carre Pizza  Rs.11,588.50
1     The Green Garden Pizza  Rs.13,955.75
2  The Spinach Supreme Pizza  Rs.15,277.75
3    The Mediterranean Pizza  Rs.15,360.50
4    The Spinach Pesto Pizza  Rs.15,596.00

In [69]:
#SQL 
#install microsoft sql server download
'''SQL Server 2025 Developer
Download Standard Developer edition'''
#in basic 
#connect now
#dwn sql server management studio 2022 installer
'''browse-> local->choose connection -> enable trust servervcertificate
mandatory ani tick then connect->'''

'browse-> local->choose connection -> enable trust servervcertificate\nmandatory ani tick then connect->'